/// The stable protocol name of one of the 47 public MCP tools.
public enum ToolOperation: String, Sendable, Hashable, CaseIterable {
    case callReadToolsBatch = "call_read_tools_batch"
    case capturePane = "capture_pane"
    case captureSince = "capture_since"
    case findPaneByPosition = "find_pane_by_position"
    case getPaneInfo = "get_pane_info"
    case getServerInfo = "get_server_info"
    case getSessionInfo = "get_session_info"
    case getTmuxVariables = "get_tmux_variables"
    case getWindowInfo = "get_window_info"
    case listPanes = "list_panes"
    case listSessions = "list_sessions"
    case listWindows = "list_windows"
    case searchPanes = "search_panes"
    case showEnvironment = "show_environment"
    case showHooks = "show_hooks"
    case showOption = "show_option"
    case snapshotPane = "snapshot_pane"
    case waitForText = "wait_for_text"

    case enterCopyMode = "enter_copy_mode"
    case exitCopyMode = "exit_copy_mode"
    case moveWindow = "move_window"
    case renameSession = "rename_session"
    case renameWindow = "rename_window"
    case resizePane = "resize_pane"
    case resizeWindow = "resize_window"
    case selectLayout = "select_layout"
    case selectPane = "select_pane"
    case selectWindow = "select_window"
    case setHistoryLimit = "set_history_limit"
    case setMouseEnabled = "set_mouse_enabled"
    case setPaneTitle = "set_pane_title"
    case signalChannel = "signal_channel"
    case swapPane = "swap_pane"
    case waitForChannel = "wait_for_channel"

    case createSession = "create_session"
    case createWindow = "create_window"
    case pasteText = "paste_text"
    case respawnPane = "respawn_pane"
    case runShellCommand = "run_shell_command"
    case sendKeys = "send_keys"
    case sendKeysBatch = "send_keys_batch"
    case setSynchronizePanes = "set_synchronize_panes"
    case splitWindow = "split_window"

    case clearPaneScrollback = "clear_pane_scrollback"
    case killPane = "kill_pane"
    case killSession = "kill_session"
    case killWindow = "kill_window"
}
