#!/usr/bin/env python3
"""Put the benchmark's own numbers into the documentation.

A table copied by hand is right on the day it is copied. This runs the
benchmark and splices what it prints between the markers in every file that
carries them, so the documented process counts are the ones the code actually
produces.

    python3 Scripts/update_mode_matrix.py           # rewrite the tables
    python3 Scripts/update_mode_matrix.py --check   # fail if any is stale

Several pages show these numbers because they are read by different people in
different places, and each takes the tables its own subject calls for. All are
written from one benchmark run — a second copy maintained by hand is the one
that goes stale.

Only the counts are written — processes started and round trips made. They are
exact and repeat every run; the timings alongside them are medians that move
with the machine, and pinning those would make the check fail for reasons that
say nothing about the code.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import shlex
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCC = ROOT / "Sources" / "LibTmux" / "LibTmux.docc"
HEADER = "<!-- generated by `swift run libtmux-bench --markdown`; do not edit -->"

#: Which file gets which tables. A page shows the comparison it is about, so
#: the streaming page carries only the streaming one rather than a copy of
#: everything the benchmark measures.
TARGETS = {
    DOCC / "Modes.md": ("mode-matrix", ("modes", "noticing")),
    ROOT / "README.md": ("mode-matrix", ("modes", "noticing")),
    DOCC / "Streaming.md": ("noticing-matrix", ("noticing",)),
}


def measured() -> dict[str, str]:
    """Run the benchmark and return each table it prints, by name."""
    # `swift` is not always on PATH — a toolchain manager may front it — so
    # the command is overridable rather than assumed.
    swift = shlex.split(os.environ.get("SWIFT", "swift"))
    result = subprocess.run(
        [*swift, "run", "libtmux-bench", "--markdown"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        # The benchmark stops itself when a count varies between runs, and the
        # reason is on its standard error. Swallowing that leaves a CI failure
        # here saying only that a subprocess died.
        print(result.stderr, file=sys.stderr, end="")
        print(f"benchmark exited {result.returncode}", file=sys.stderr)
        raise SystemExit(1)

    tables: dict[str, list[str]] = {}
    current: list[str] | None = None
    for line in result.stdout.splitlines():
        name = line.removeprefix("<!-- section: ").removesuffix(" -->")
        if name != line:
            current = tables.setdefault(name, [])
        elif current is not None and line.strip():
            current.append(line)
    if not tables:
        print("benchmark printed no named tables", file=sys.stderr)
        raise SystemExit(1)
    return {name: "\n".join(rows) for name, rows in tables.items()}


def spliced(document: str, marker: str, table: str) -> str:
    """Return `document` with `table` between its markers."""
    start, end = f"<!-- {marker}:start -->", f"<!-- {marker}:end -->"
    head, rest = document.split(start, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{start}\n\n{table}\n\n{end}{tail}"


def main() -> int:
    """Rewrite every target, or report which have gone stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if stale")
    args = parser.parse_args()

    documents = {}
    for target, (marker, _) in TARGETS.items():
        document = target.read_text()
        for edge in ("start", "end"):
            if f"<!-- {marker}:{edge} -->" not in document:
                print(f"no {marker}:{edge} marker in {target.name}", file=sys.stderr)
                return 1
        documents[target] = document

    # One run feeds every target: measuring twice would let two pages disagree,
    # which is the failure this script exists to prevent.
    tables = measured()
    missing = {
        name
        for _, sections in TARGETS.values()
        for name in sections
        if name not in tables
    }
    if missing:
        names = ", ".join(sorted(missing))
        print(f"benchmark printed no {names} table", file=sys.stderr)
        return 1

    def rendered(target: pathlib.Path) -> str:
        _, sections = TARGETS[target]
        return "\n\n".join([HEADER, *(tables[name] for name in sections)])

    stale = [
        target
        for target, document in documents.items()
        if spliced(document, TARGETS[target][0], rendered(target)) != document
    ]
    if not stale:
        print("mode matrix is current")
        return 0
    if args.check:
        names = ", ".join(target.name for target in stale)
        print(
            f"mode matrix is stale in {names}; run Scripts/update_mode_matrix.py",
            file=sys.stderr,
        )
        return 1
    for target in stale:
        target.write_text(
            spliced(documents[target], TARGETS[target][0], rendered(target))
        )
        print(f"updated {target.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
